import Header from "~/components/Header"
import GlobalProvider from "~/components/GlobalProvider"
import "~/style/root.scss"
export const metadata = {
  title: "POST_CRUD",
  description: "Generated by kslhk8",
}
// import { headers } from 'next/headers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  /*
  * 404 page와 500 page(maintainance)일 때 Header 안보이게 하기위해서 구현
  // */
  // const headersList = headers();
  // const pathName = headersList.get("x-invoke-path") || "";
  return (
    <html lang="en">
      <body>
        {/* {(!pathName.includes('maintainance') && !pathName.includes('not-found')) && <Header />} */}
        <Header />
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  )
}
