import Header from "~/components/Header"
import GlobalProvider from "~/components/GlobalProvider"
import Toast from "~/components/Toast"
import "~/style/root.scss"
export const metadata = {
  title: "POST_CRUD",
  description: "Generated by kslhk8",
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <GlobalProvider>{children}</GlobalProvider>
        <Toast />
      </body>
    </html>
  )
}
